import { useEffect, useState } from 'react'
import axios from 'axios'
type Point={timestamp:string;price:number}
const price=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n<2?6:2}).format(n)
export default function PriceChart({id,name}:{id:string;name:string}){
 const [points,setPoints]=useState<Point[]>([]),[error,setError]=useState(false),[days,setDays]=useState(30),[selected,setSelected]=useState<number|null>(null)
 useEffect(()=>{let current=true;setPoints([]);setError(false);setSelected(null);axios.get<{points:Point[]}>(`${import.meta.env.BASE_URL}data/history/${id.replace('crypto-','')}.json`).then(({data})=>{if(!Array.isArray(data.points)||data.points.length<2)throw new Error();if(current)setPoints(data.points)}).catch(()=>{if(current)setError(true)});return()=>{current=false}},[id])
 if(error)return <section className="price-history"><h3>Price history</h3><p className="muted">History is unavailable for this instrument.</p></section>
 if(!points.length)return <p role="status" className="muted">Loading price history…</p>
 const last=Date.parse(points[points.length-1].timestamp),data=points.filter(p=>Date.parse(p.timestamp)>=last-days*86400000)
 const start=Date.parse(data[0].timestamp),span=last-start||1,min=Math.min(...data.map(p=>p.price)),max=Math.max(...data.map(p=>p.price)),padding=(max-min)*.1||max*.001||.01,low=min-padding,high=max+padding
 const x=(p:Point)=>70+(Date.parse(p.timestamp)-start)/span*680,y=(p:Point)=>240-(p.price-low)/(high-low)*195
 const line=data.map(p=>`${x(p)},${y(p)}`).join(' '),index=Math.min(selected??data.length-1,data.length-1),active=data[index],change=(data[data.length-1].price/data[0].price-1)*100
 return <section className="price-history"><div className="widget-heading"><div><p className="eyebrow">{name} / USD</p><h2>Price history</h2></div><div className="filters">{[7,30].map(n=><button key={n} className={days===n?'selected':''} aria-pressed={days===n} onClick={()=>{setDays(n);setSelected(null)}}>{n}D</button>)}</div></div><div className="history-readout"><strong>{price(active.price)}</strong><span className="muted">{new Date(active.timestamp).toLocaleString('en-US',{timeZone:'America/Chicago',timeZoneName:'short'})}</span><span className={change>=0?'positive':'negative'}>{change>=0?'+':''}{change.toFixed(2)}% over {days} days</span></div><svg className="price-chart" viewBox="0 0 800 290" role="img" aria-label={`${name} price history in US dollars over ${days} days`} onMouseMove={e=>{const rect=e.currentTarget.getBoundingClientRect(),time=start+Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width*800/680-70/680))*span;let nearest=0;data.forEach((p,n)=>{if(Math.abs(Date.parse(p.timestamp)-time)<Math.abs(Date.parse(data[nearest].timestamp)-time))nearest=n});setSelected(nearest)}} onMouseLeave={()=>setSelected(null)}>{[0,1,2,3].map(n=>{const v=low+(high-low)*n/3,pos=240-n*65;return <g key={n}><line x1="70" x2="750" y1={pos} y2={pos} className="chart-grid"/><text x="60" y={pos+4} textAnchor="end">{price(v)}</text></g>})}<polyline points={line} className="yield-line"/><line x1={x(active)} x2={x(active)} y1="45" y2="240" className="chart-grid"/><circle cx={x(active)} cy={y(active)} r="5" className="yield-point"/>{[0,.5,1].map(f=><text key={f} x={70+680*f} y="270" textAnchor="middle">{new Date(start+span*f).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'America/Chicago'})}</text>)}</svg><label className="history-slider">Explore observations<input type="range" min="0" max={data.length-1} value={index} onChange={e=>setSelected(Number(e.target.value))}/></label><p className="chart-note">Sugra Crypto · Historical snapshot · Hover or use the slider to inspect prices.</p></section>
}
